version: '3.8'

services:
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: document_rag_db
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: .
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017/
      - DB_NAME=document_rag_db
      - CORS_ORIGINS=http://localhost:3000,https://your-frontend-domain.com
      - HOST=0.0.0.0
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build: ./frontend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  mongodb_data:
